"""KV4P vendor envelope constants."""

from __future__ import annotations

KV4P_PROTOCOL_VERSION = 0x01
KV4P_VENDOR_PREFIX = b"KV4P"
KV4P_VENDOR_HEADER_LEN = 6

# Host -> device
COMMAND_HOST_TX_AUDIO = 0x07
COMMAND_HOST_DESIRED_STATE = 0x0D

# Device -> host
COMMAND_DEBUG_INFO = 0x01
COMMAND_DEBUG_ERROR = 0x02
COMMAND_DEBUG_WARN = 0x03
COMMAND_DEBUG_DEBUG = 0x04
COMMAND_DEBUG_TRACE = 0x05
COMMAND_HELLO = 0x06
COMMAND_RX_AUDIO = 0x07
COMMAND_RX_AUDIO_ADPCM = 0x0C
COMMAND_WINDOW_UPDATE = 0x09
COMMAND_DEVICE_STATE = 0x0B
